mutation($id: UUID, $user_id: UUID!, $event_id: UUID!, $invitationtype_id: UUID!) {
  result: eventUserInsert(eventUser: {
    id: $id, 
    userId: $user_id, 
    eventId: $event_id, 
    invitationtypeId: $invitationtype_id
  }) {
    __typename
    ...Presence
    ...on InsertError {
      msg
    }
  }
}

fragment Presence on PresenceGQLModel {
  id
  lastchange
  event {
    id
    name
  }
}
