mutation($user_id: UUID!, $event_id: UUID!,$lastchange: DateTime!) {
  result: eventUserDelete(eventUser: {
    userId: $user_id, eventId: $event_id, lastchange:$lastchange
  }) {
     
    msg
   
  }
}
