mutation ($id: UUID!, $lastchange: DateTime!, $invitationtype_id: UUID, $presencetype_id: UUID) {
  result: eventUserUpdate(
    eventUser: { id: $id, lastchange: $lastchange, invitationtypeId: $invitationtype_id, presencetypeId: $presencetype_id }
  ) {
    __typename
    ...EventUser
    ...on PresenceGQLModelUpdateError {
      msg
    }
  }
}

fragment EventUser on PresenceGQLModel {
  id
  lastchange
  event {
    id
    name
  }
}
